#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libXfixes
Version  : 5.0.1
Release  : 6
URL      : http://xorg.freedesktop.org/releases/individual/lib/libXfixes-5.0.1.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libXfixes-5.0.1.tar.bz2
Summary  : X Fixes  Library
Group    : Development/Tools
License  : HPND
Requires: libXfixes-lib
Requires: libXfixes-doc
BuildRequires : pkgconfig(fixesproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
Xfixes
XFIXES Extension
Version 2.0.1
2002-10-4
This package contains header files and documentation for the XFIXES
extension.  Library and server implementations are separate.

%package dev
Summary: dev components for the libXfixes package.
Group: Development
Requires: libXfixes-lib

%description dev
dev components for the libXfixes package.


%package doc
Summary: doc components for the libXfixes package.
Group: Documentation

%description doc
doc components for the libXfixes package.


%package lib
Summary: lib components for the libXfixes package.
Group: Libraries

%description lib
lib components for the libXfixes package.


%prep
%setup -q -n libXfixes-5.0.1

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/Xfixes.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
